apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    # labels do postgres-pod.yaml
    name: result-app-pod
    app: demo-voting-app